# Site settings
title: An Unofficial Guide to Canadian Immigration
email: anthonylukach+immigration@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A guide to the Canadian Family Sponsorship Visa.
baseurl: "/unofficial-guide-to-canadian-immigration" # the subpath of your site, e.g. /blog/
url: "http://alukach.com/unofficial-guide-to-canadian-immigration" # the base hostname & protocol for your site
twitter_username: anthonylukach
# github_username:  jekyll

# Build settings
markdown: kramdown
